# Generated by Django 5.0.6 on 2024-07-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50, verbose_name='Artist Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50, verbose_name='Album Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist', verbose_name="Album's Artist")),
            ],
            options={
                'verbose_name': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songThumbnail', models.ImageField(help_text='.jpg, .png, .jpeg, .svg supported', upload_to='thumbnail/', verbose_name='Song Thumbnail')),
                ('song_name', models.CharField(max_length=50, verbose_name='Song Name')),
                ('song', models.FileField(help_text='mp3* required', upload_to='songs/', verbose_name='song')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Song Album')),
            ],
            options={
                'verbose_name': 'Song',
            },
        ),
    ]
