# Generated by Django 5.0.6 on 2024-07-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(null=True, upload_to='artist/', verbose_name='Artist Image'),
        ),
    ]
